### ISSUE TITLE
什么玩意？

### ISSUE THREAD

**Issue by tobyhui** [zcy-inc/skuPathFinder-back#1]
![image](https://user-images.githubusercontent.com/20480609/134378509-f4beae7e-944d-400c-9d88-5dc0abe76d43.png)
搞个那么神秘，说了一大堆算法、图
代码一跑，什么玩意？

**Comment by zcy-yunyun** [comment]
亲，稍安勿躁，最新的同行规格移除已经添加，更新master代码即可哦
